discovery:
  image: statim/servicediscovery
  ports:
    - "8761:8761"

authserver:
  image: statim/authserver
  links:
    - discovery
    
edgeserver:
  image: statim/edgeserver
  ports:
    - "80:5000" 
  links:
    - authserver
    - discovery
    
orderendpoint:
  image: statim/orderendpoint
  links:
    - authserver
    - discovery
    - receiveorderservice
    
receiveorderservice:
  image: statim/receiveorderservice
  links:
    - authserver
    - discovery
    - orderservice
    
orderservice:
  image: statim/orderservice
  links:
    - authserver
    - discovery

  