server:
  port: 0
  
#security:
#  ignored: /**   

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:5000/uaa/user

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
#    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_URL}
#    availabilityZones:
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}

#stores:
#  ribbon:
#    ServerListRefreshInterval: 1000

logging:
  level:
    se.callista: INFO
    
---
# For deployment in Docker containers
spring:
  profiles: docker

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    
      
security:
  oauth2:
    resource:
      userInfoUri: http://authserver:8080/uaa/user      