server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
#    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.0.22:8761/eureka
#    availabilityZones:
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}

#stores:
#  ribbon:
#    ServerListRefreshInterval: 1000

logging:
  level:
    se.callista: INFO