server:
  port: 0
  contextPath: /uaa
  
security:
  user:
    #name: user
    password: password1


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
#    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_URL}
#    availabilityZones:
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}

logging:
  level:
    org.springframework.security: DEBUG