info:
  component: Zuul Server

eureka:
  client:  
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_URL}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    orderendpoint:
      sensitiveHeaders:
      path: /orderendpoint/**
#      stripPrefix: false
      serviceId: orderendpoint
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      serviceId: authserver
      stripPrefix: false
    simpleapp:
      path: /simple/**
      serviceId: simpleapp

server:
  port: 5000
  
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user 

#management:
#  security:
#    enabled: false      

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

---
# Eureka instance 1 when used on Docker
spring:
  profiles: docker1
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: true
    fetchRegistry: true    
