info:
  component: Zuul Server

eureka:
  client:  
    serviceUrl:
      defaultZone: {$SERVICE_DISCOVERY_URL}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    orderendpoint:
      path: /orderendpoint/**
#      stripPrefix: false
      serviceId: orderendpoint

server:
  port: 9000
  
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user  
      
#management:
#  security:
#    enabled: false      

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
