server:
  port: 0

service:
  defaultMinMs: 100
  defaultMaxMs: 200

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://192.168.0.22:8761/eureka
      defaultZone: {$SERVICE_DISCOVERY_URL}
#security:
#  ignored: /**     

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user      